version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/aigis-doc

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/aigis-doc

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/aigis-doc
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - run: npm run codecov
      - run: bash <(curl -s https://codecov.io/bash) -t 7337b222-3c4c-449d-9503-86c9bee5d88a

workflows:
  version: 2
  build:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
